/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Video = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'youtubeUrl' : IDL.Text,
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'userMessage' : IDL.Text,
  'assistantResponse' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'clearChatHistory' : IDL.Func([], [], []),
  'generateVideoFrames' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getHighScore' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'saveHighScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'youtubeUrl' : IDL.Text,
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'userMessage' : IDL.Text,
    'assistantResponse' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'clearChatHistory' : IDL.Func([], [], []),
    'generateVideoFrames' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getHighScore' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'saveHighScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };