/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'userMessage' : string,
  'assistantResponse' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface Video {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'description' : string,
  'category' : string,
  'youtubeUrl' : string,
}
export interface _SERVICE {
  'addVideo' : ActorMethod<[string, string, string, string, string], undefined>,
  'clearChatHistory' : ActorMethod<[], undefined>,
  'generateVideoFrames' : ActorMethod<[string], Array<string>>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getHighScore' : ActorMethod<[string], bigint>,
  'getVideosByCategory' : ActorMethod<[string], Array<Video>>,
  'saveHighScore' : ActorMethod<[string, bigint], undefined>,
  'sendMessage' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];